import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./components/header";
import { Ticker } from "./components/ticker";
import { Footer } from "react-day-picker";
import { FloatingContacts } from "./components/floating-contacts";
import { SiteFooter } from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DEV PỒ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <Header />
        <Ticker />

        <main className="min-h-screen">{children}</main>

        <SiteFooter />
        <FloatingContacts />
      </body>
    </html>
  );
}
